### ISSUE TITLE
isMobile function

### ISSUE THREAD

**Issue by IsmetAkyurek** [cemiluzunhasan/cemiluzunhasan.com-v2#1]
Please do not use isMobile function since it is a "Ağbiiii" use.

**Comment by cemiluzunhasan** [comment]
We don't use isMobile functions in this project. And we won't use isMobile function in any other project no more.

**Comment by IsmetAkyurek** [comment]
<img width="555" alt="screen shot 2019-02-12 at 14 43 59" src="https://user-images.githubusercontent.com/13468982/52633182-aa807300-2ed4-11e9-81da-e09d84e93827.png">
I just saw that isMobile is in the cemil.js file.

**Comment by cemiluzunhasan** [comment]
There's no cemil.js
